### ISSUE TITLE
Add full media modifier to build full row layouts

### ISSUE THREAD

**Issue by lecoueyl** [iotacss/iotacss#17]
Media object is a great way to make simpler layout using the modifier `o-media-full` like this
```
<div class="o-media o-media--full">
  <div class="o-media__fixed">
     ...
  </div>
  <div class="o-media__fluid">
     ...
  </div>
</div>
```

It will render one fixed sized row and one fluid row using all the vertical height of the parent and making the content scrollable.

<img width="815" alt="capture d ecran 2018-02-14 a 13 52 22" src="https://user-images.githubusercontent.com/8327054/36188362-fbc0d926-118e-11e8-9771-d4cf9d7c83a3.png">

iotacss code:
```
$iota-objs-media-full-name: 'full' !default;

.#{$iota-objs-media-var-media-mod + $iota-objs-media-full-name} {
  height: 100%;
  overflow: hidden;

  & > .#{$iota-objs-media-var-media-fixed},
  & > .#{$iota-objs-media-var-media-fluid} {
    height: 100%;
    overflow: auto;
  }
}
```

**Comment by andrewckor** [comment]
Hey @lecoueyl this is a nice suggestion. Even though this is not considered media object anymore, it's just a hacked version of using it.

I prefer to build this the right way by making a new fluid version of grid, that lets you build interfaces like this.
```
e.x. o-grid--fluid
```

**Comment by harby** [comment]
Hey @lecoueyl, sorry for not responding earlier on that. This is a great idea but it's too opinionated for such a general structural object and I would like to avoid it. I have several ideas about elements like these on v2, but it's still under construction. I will try to start sharing ideas on this repo soon.

**Comment by lecoueyl** [comment]
Thank you for you answer and happy to know you are still working on it!
I will close this issue for now then
