### ISSUE TITLE
The documentation site is not accessible.

### ISSUE THREAD

**Issue by MarjaE2** [iotacss/iotacss#21]
The documentation site doesn't scroll together. It relies on two columns, and users are expected to scroll one column at a time, with sheer in the middle of the window.

This makes it harder to scroll, and can trigger migraines for users with visual processing issues.

**Comment by harby** [comment]
Hi @MarjaE2, thank you for your feedback.

We are now in the process of completely rebuilding this website and we will make it open-source so everybody can contribute. Accessibility will be one of our main priorities this time.

I will keep this issue open until the new website is up.
