### ISSUE TITLE
Grid with extra responsive gutters does not work

### ISSUE THREAD

**Issue by ghost** [iotacss/iotacss#24]
Hi, 

if I set (according the documentation: https://www.iotacss.com/docs/objects/grid/):

```
$iota-objs-grid-gutter: (
  small: (
    null : 5px,
    sm   : 10px
  )
);
```

it does not seem to render responsive gutter styles. I had a closer look into the source file (https://github.com/iotacss/iotacss/blob/master/modules/iotacss-objs-grid/_objects.grid.scss), and that variable is not evaluated there.

**Comment by timonweber** [comment]
I think the variable you are looking for is `$iota-objs-grid-gutter-default`.

But you are right, the documentation is incorrect in this regard.

**Comment by ghost** [comment]
I tried with `$iota-objs-grid-gutter-default` as well. Does not return the desired result. And I cannot see any breakpoint specific styles in this [file](https://github.com/iotacss/iotacss/blob/master/modules/iotacss-objs-grid/_objects.grid.scss).

**Comment by harby** [comment]
Hi @dp-thomas, here's the thing. $iota-objs-grid-gutter-default is the default gutter size and the syntax should be like this:

```
$iota-objs-grid-gutter-default: (
  null: 5px,
  sm: 10px
);
```

Now, you seem like you want to create a small size. In this case, you should use the `extra gutters`:

```
$iota-objs-grid-gutter-extra: (
  small: (
    null : 5px,
    sm   : 10px
  )
);
```

That will generate an `o-grid--small` class which will have 5px gutter in a mobile and 10px gutter in tablets and up.

**Comment by harby** [comment]
Also, check the documentation here: https://www.iotacss.com/docs/objects/grid/. It's described in detail. Feel free to ask any more questions!

**Comment by ghost** [comment]
@harby thanks for the detailed explanation. Makes sense. Still, [here in the last section](https://www.iotacss.com/docs/objects/grid/) its described with different variable names. That is what confused me
