### ISSUE TITLE
Autosizing equal width size utility

### ISSUE THREAD

**Issue by Windvis** [iotacss/iotacss#5]
In a project I'm working on I needed a sizer helper class which makes elements with the class equal width no matter the items inside the grid.

I extended the size utility to generate this class (including a class for each breakpoint if the responsive flag was set to true) with the default namespace of "equal-width" but this is configurable like the other iotacss namespaces.

So with the default iotacss config it would be: `.u-equal-width`, `.u-equal-width@sm`, ...

Is this something that could be useful for iotacss base? If so, I can create a PR.

**Comment by harby** [comment]
This is a good addition and has been asked in the past. I think though, this should be a part of the Grid Object and not of the Size Utility. Same as the equal-height option.

**Comment by Windvis** [comment]
Yes, that was my first intention as well, the downside of that is that you can't toggle this behavior from a specific breakpoint (for example, from tablets onwards). The benefit of it being part of the Size utility is that it also generates responsive classes (like in my example above).

The downside of the Size Utility version is that you have to make sure that you apply the class to every child element in the grid.

**Comment by harby** [comment]
You can toggle the behavior by applying a Size Utility class, for example:

```
<div class="o-grid o-grid--equal-width">
  <div class="o-grid__col u-1/2@xs">
    Column size that is equal width in all sizes except mobile, where it's half width
  <div>
</div>
```

A flexbox grid column, if no width applied, it will be equal-width. Does this make sense?

**Comment by harby** [comment]
I assume this is fixed. Closing.
